### ISSUE TITLE
`items` are always missing on TypeScript models

### ISSUE THREAD

**Issue by TheDutchCoder** [aws-amplify/amplify-codegen#160]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

16.0.0

### Amplify CLI Version

4.50.0

### What operating system are you using?

Mac

### Amplify Categories

api

### Amplify Commands

codegen

### Describe the bug

Consider the following schema:
```graphql
type User
@model
@key(fields: [ "id", "businessId" ])
@key(name: "ByBusiness", fields: [ "businessId","id" ], queryField: "usersByBusiness")
@key(name: "ByEmail", fields: [ "email" ], queryField: "usersByEmail")
{
  id: ID! #cognitoId
  name: String!
  groups: [GroupMembership] @connection(fields: [ "id" ])
}
```
This will generate the following model:
```graphql
export declare class User {
  readonly id: string;
  readonly name: string;
  readonly groups?: (GroupMembership | null)[];
}
```
With the following query:
```graphql
export const listUsers = /* GraphQL */ `
  query ListUsers(
    $id: ID
  ) {
    listUsers(
      id: $id
    ) {
      items {
        id
        name
        groups {
          items {
```

However this schema does not line up with the query, as the query returns `groups.items` and TypeScript will tell you that `items` doesn't exist on `groups` (because it's always missing from the class).

This happens for literally any array relation and it's a major pain to have to create manual interfaces or types for each and every query/mutation that has some sort of array returned.

### Expected behavior

codegen to actually include the `items` prop wherever an array is used.

### Reproduction steps

1. Create a similar schema
2. Run `codegen` and `codegen types`
3. See the missing `items` property

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
type User
@model
@key(fields: [ "id", "businessId" ])
@key(name: "ByBusiness", fields: [ "businessId","id" ], queryField: "usersByBusiness")
@key(name: "ByEmail", fields: [ "email" ], queryField: "usersByEmail")
{
  id: ID! #cognitoId
  name: String!
  groups: [GroupMembership] @connection(fields: [ "id" ])
}
```

</details>

**Comment by AaronZyLee** [comment]
@TheDutchCoder The model file you provided is generated by `amplify codegen models` but not `amplify codegen types`. Could you check out your `.graphqlconfig.yml` file which should be at your project root? By default if you are a typescript user, this file should be `src/API.ts`. And this file is the exact type declaration to line up your graphql queries.

**Comment by TheDutchCoder** [comment]
Strange, I did not get notified of your reply, sorry for this later reaction.

Our amplify dir is actually at the root level of our monorepo (because we need to share the queries/mutations/subscriptions/types/etc between different projects), so we have a custom config:

```yml
projects:
  creativelayeroms:
    schemaPath: amplify/backend/api/creativelayeroms/build/schema.graphql
    includes:
      - api/graphql/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: api/graphql
        region: us-east-1
        apiId: null
        maxDepth: 6
extensions:
  amplify:
    version: 3
```

I'm wondering if the JavaScript target is the problem. We can't go full TS for all our projects, mainly due to the Lambda's.
