### ISSUE TITLE
GraphQL Transformer not providing $condition input for update mutation

### ISSUE THREAD

**Issue by djwood** [aws-amplify/amplify-codegen#230]
**Do you want to request a feature or report a bug?**
Bug

**What is the current behavior?**
I've seen in many examples (e.g. https://github.com/dantasfiles/ExploreAmplifyAPI) where $condition input (in the form of Model{name}ConditionInput) is generated onto the create, update, and delete mutations (presumably via codegen). However, I'm not seeing this in my implementation:

**To Reproduce**

_schema.graphql:_

```
type Order @model
  @key (name: "byQueue", fields: ["queue"], queryField: "ordersByQueue")
  @auth (rules: [
      { allow: private, provider: iam, operations: [create, read, update, delete] },
      { allow: groups, groups: ["admin", "support"], operations: [create, read, update, delete] },
    ]
  ) { 
   id: ID! 
   restaurantID: ID!
   order: AWSJSON
   executionArn: String
   queue: String
   queStatus: String
   dispOps: AWSJSON
   abortDispatch: Boolean
   isSimDispatch: Boolean
   restaurant: Restaurant @connection(fields: ["restaurantID"]) 
   meta: AWSJSON
} 
```

_Grahpql transformer output (mutation.js):_
```
export const updateOrder = /* GraphQL */ 
  mutation UpdateOrder($input: UpdateOrderInput!) {
    updateOrder(input: $input) {
      id
      restaurantID
     ...
   }
 }
```

Expected mutation:
```
export const updateOrder = /* GraphQL */ `
  mutation UpdateOrder($input: UpdateOrderInput!, $condition: ModelOrderConditionInput) {
    updateOrder(input: $input, condition: $condition) {
      id
      restaurantID
     ...
   }
 }
```

NOTE: I get around this by manually adding `$condition: ModelOrderFilterInput` to the schema in AWS console after every amplify push that updates the API and works but obviously not an ideal solution...

Additional environment details
- OS version: 
   macOS Mojave 10.14.6
- Output of amplify --version:
  5.0.0

Did this work in previous versions?:
No

Additional Context:
Initially, my .graphqlconfig.yml was:
```
projects:
  wl1:
    schemaPath: amplify/backend/api/wl1/build/schema.graphql
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        maxDepth: 6
extensions:
  amplify:
    version: 3
```
Subsequently, I manually updated the yml to ```amplify: version: 5```  but still get the same results.
