### ISSUE TITLE
Nested Typescript Types are not generated as Types

### ISSUE THREAD

**Issue by andre-qup** [aws-amplify/amplify-codegen#32]
**Describe the bug**
When running ```amplify codegen``` with Typescript option, if the Schema contains nested Types, they will be generated as plain objects with no proper Type.

**Amplify CLI Version**
4.19.0

**To Reproduce**
 Consider the following Schema: 
``` 
type Query { 
    listTest(from: AWSDateTime!, to: AWSDateTime!): myTypeConnection 
} 
type myTypeConnection {
    items: [myType]
    nextToken: String
}
type myType {
    id: ID! some_string: String!
    some_date: AWSDateTime!
}
 ```
The resulting codegen TS file will contain:
```
export type ListTestQuery = {
  listTest:  {
    __typename: "myTypeConnection",
    items:  Array< {
      __typename: "myType",
      id: string,
      some_string: string,
      some_date: string
    } | null > | null,
    nextToken: string | null,
  } | null,
};
```

**Expected behavior**
Since we defined proper types in GraphQL schema, I expected all GraphQL types to be transpiled into Typescript Types. Something like:
```
export type MyType {
  id: string,
  some_string: string,
  some_date: string
}

export type MyTypeConnection {
    items: Array< MyType | null > | null,
    nextToken: string | null,
}

export type ListTestQuery = {
  listTest: MyTypeConnection | null,
};
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.4 LTS
 - Node v11.15.0

**Additional context**
If this is not a bug kindly let me know and I'll open a feature request. I see no reason why any Type defined in the Schema can't become a Type in generated Typescript code, especially since the addition of the ```--max-depth``` which I tried to no avail. Thus, I consider this a bug.

Thanks in advance

**Comment by amcdnl** [comment]
@phani-srikar ->

I ran into this too and ended up not using the codegen from amplify but using https://graphql-code-generator.com/docs/getting-started/index directly. Here is my config for that:

```
overwrite: true
schema:
  - ${REACT_APP_SCHEMA_URL}:
      method: GET
documents: "src/core/graphql/*.ts"
generates:
  src/core/graphql/schema.graphql:
    plugins:
      - schema-ast:
          includeDirectives: true
          commentDescriptions: true

  src/core/graphql/types.ts:
    plugins:
      - add:
          content: '/* eslint-disable */'
      - typescript:
          skipTypename: true

  src/core/graphql/operations.ts:
    plugins:
      - add:
          content: '/* eslint-disable */'
      - named-operations-object:
          identifierName: Operations

  src/core/graphql/:
    preset: near-operation-file
    presetConfig:
      baseTypesPath: types.ts
      extension: .ts
    plugins:
      - add:
          content: '/* eslint-disable */'
      - typescript-operations:
          namingConvention: pascal-case#pascalCase
          skipTypename: true
          # preResolveTypes: true
      - typescript-document-nodes:
          namingConvention: camel-case#camelCase
```

This config extracts the types like you are requesting:

![image](https://user-images.githubusercontent.com/227909/106746915-307db300-65f1-11eb-841c-fd5a6eb1a865.png)

I also made a new endpoint in my app that would pull the graphql schema via api ( I have a issue logged for that ) to make this work:

```ts
import { AppSync } from 'aws-sdk';
import { Request, Response } from 'express';
import ono from '@jsdevtools/ono';

const client = new AppSync();

const apiId = process.env.API_API_GRAPHQLAPIIDOUTPUT as string;
const apiKey = process.env.API_API_GRAPHQLAPIKEYOUTPUT as string;

export async function schemaHandler(req: Request, res: Response) {
  try {
    const req = client.getIntrospectionSchema({
      apiId,
      format: 'JSON',
      includeDirectives: true
    });

    req.on('build', () => {
      req.httpRequest.headers['x-api-key'] = apiKey;
    });

    const result = await req.promise();

    return res.type('application/json').send((result.schema as any).toString());
  } catch (error) {
    throw ono({ status: 500 }, `Failed to get schema`);
  }
}
```
