### ISSUE TITLE
Codegen Model Types

### ISSUE THREAD

**Issue by ChrisChares** [aws-amplify/amplify-codegen#34]
**Is your feature request related to a problem? Please describe.**

It's frustrating that codegen doesn't generate typescript model types.  If I define a @model in my schema consisting of:

```graphql
type Room
  @model 
{
  id: ID!
  name: String!
  primaryColor: String
  iconName: String
}
```

Codegen will generate literally thousands of lines of code.  For example:

```typescript
export type GetRoomQuery = {
  getRoom:  {
    __typename: "Room",
    id: string,
    name: string,
    primaryColor: string | null,
    iconName: string | null,
};

export type ListRoomsQuery = {
  listRooms:  {
    __typename: "ModelRoomConnection",
    items:  Array< {
      __typename: "Room",
      id: string,
      name: string,
      primaryColor: string | null,
      iconName: string | null,
};

export type CreateRoomInput... etc etc
```

But it never generates a simple `Room` model interface. We have to create and maintain this manually.  **Why?** Is there a reason for this?

**Describe the solution you'd like**

For this specific example, somewhere in the thousands of lines of code in `API.ts` I would expect to find:

```typescript
export interface Room {
  id: string;
  name: string;
  primaryColor?: string;
  iconName?: string;
}
```

**Describe alternatives you've considered**

Manual creation and maintenance of model types.

Thanks for your time,
Chris

**Comment by amcdnl** [comment]
I actually ended up removing the amplify codegen all together. Here is what I came up with:

```yml
overwrite: true
schema:
  - ${REACT_APP_SCHEMA_URL}:
      method: GET
documents: "src/core/graphql/*.ts"
generates:
  src/core/graphql/schema.graphql:
    plugins:
      - schema-ast:
          includeDirectives: true
          commentDescriptions: true

  src/core/graphql/types.ts:
    plugins:
      - add:
          content: '/* eslint-disable */'
      - typescript:
          skipTypename: true

  src/core/graphql/operations.ts:
    plugins:
      - add:
          content: '/* eslint-disable */'
      - named-operations-object:
          identifierName: Operations

  src/core/graphql/:
    preset: near-operation-file
    presetConfig:
      baseTypesPath: types.ts
      extension: .ts
    plugins:
      - add:
          content: '/* eslint-disable */'
      - typescript-operations:
          namingConvention: pascal-case#pascalCase
          skipTypename: true
          # preResolveTypes: true
      - typescript-document-nodes:
          namingConvention: camel-case#camelCase
```

and then I made a REST API endpoint that would let me get the graphql schema that looks like this:

```ts
import { AppSync } from 'aws-sdk';
import { Request, Response } from 'express';

const client = new AppSync();

const apiId = process.env.API_API_GRAPHQLAPIIDOUTPUT as string;
const apiKey = process.env.API_API_GRAPHQLAPIKEYOUTPUT as string;

export async function schemaHandler(req: Request, res: Response) {
  try {
    const req = client.getIntrospectionSchema({
      apiId,
      format: 'JSON',
      includeDirectives: true
    });

    req.on('build', () => {
      req.httpRequest.headers['x-api-key'] = apiKey;
    });

    const result = await req.promise();

    return res
      .type('application/json')
      .send((result.schema as any).toString());
  } catch (error) {
    return res
      .status(500)
      .json({ success: false, errors: ['Failed to get schema'] });
  }
}
```
