### ISSUE TITLE
API types contain __typename, queries do not

### ISSUE THREAD

**Issue by eettaa** [aws-amplify/amplify-codegen#445]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-codegen/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-codegen/blob/master/CONTRIBUTING.md#bugs).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm 

### If applicable, what version of Node.js are you using?

14.18.1

### Amplify CLI Version

7.6.21 (sorry, I'm blocked by https://github.com/aws-amplify/amplify-category-api/issues/560)

### What operating system are you using?

Ubuntu

### Amplify Codegen Command

codegen

### Describe the bug

API.ts as generated by codegen has typescript types that include a string literal __typename field, e.g.
```
export type GetSavingsAccountQuery = {
  getSavingsAccount?:  {
    __typename: "SavingsAccount",
    accountId: string
    ...
}
```
But the associated graphql query in queries.ts does NOT query the __typename field:
```
  query GetSavingsAccount($accountId: ID!) {
    getSavingsAccount(accountId: $accountId) {
      accountId
      (no __typename here!)
      ...
  }
}
```

This means that trying to access __typename on a query response will always typecheck but never succeed at runtime (because that field is never returned).

Some frontend graphql clients like ApolloClient automatically append __typename to all queries, which works around this problem.  however, if you were to use the literal query as generated, it would not match the type as generated.

Is there an option to have codegen add __typename to all the queries?

### Expected behavior

all queries in queries.ts also query the __typename field, or (less preferrable to me), API.ts does not export __typename as a field in all query responses.

### Reproduction steps

Take any trivial @model-annotated type in schema
Codegen it
Inspect API.ts and queries.ts, notice one has __typename and one does not.

### GraphQL schema(s)

I have instead included a graphqlconfig.yml:
```
projects:
  projectname:
    schemaPath: path/to/schmea
    includes:
      - path/to/codegen/**/*.ts
      - path/to/custom/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: path/to/codegen/API.ts
        docsFilePath: path/to/codegen
        region: us-west-2
        apiId: null
        maxDepth: 6
extensions:
  amplify:
    version: 3
```

### Log output

<details>

```
# Put your logs below this line


```

</details>
