### ISSUE TITLE
[codegen] graphql config - multiple extension outputs from a project

### ISSUE THREAD

**Issue by uncodable** [aws-amplify/amplify-codegen#49]
**Is your feature request related to a problem? Please describe.**
I want to output typescript types to lambda functions as well as my frontend application also.

**Describe the solution you'd like**
The ability to have many extensions with the same key as `amplify` within the same project:
```yml
projects:
  Workspaces:
    schemaPath: src/graphql/Workspaces/schema.json
    includes:
      - src/graphql/Workspaces/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/utils/API.ts
        docsFilePath: src/graphql/Workspaces
        maxDepth: 2
      amplify:
        codeGenTarget: typescript
        generatedFileName: amplify/backend/foobar/API.ts
        docsFilePath: amplify/backend/foobar
        maxDepth: 2
extensions:
  amplify:
    version: 3
```

**Describe alternatives you've considered**
Having a folder in the root directory to allow types to be read from there, however it's not easy and requires extra permissions and npm won't let you read outside the main dir it's being ran from. So this will be an issue for lambda functions.

**Comment by phani-srikar** [comment]
Hi @uncodable Thank you for taking time and requesting this feature. We are working on making the codegen configuration more flexible and customizable. Please look out for an RFC on this.

**Comment by uncodable** [comment]
Thanks for the update @phani-srikar it's a blocker at the moment on my current project 👍🏻

**Comment by renebrandel** [comment]
@uncodable just wanted to let you know that we've publish an RFC to address this and other code generation issues. Would love to have your feedback!

**Comment by hackmajoris** [comment]
> @uncodable just wanted to let you know that we've publish an RFC to address this and other code generation issues. Would love to have your feedback! [aws-amplify/amplify-cli#6898](https://github.com/aws-amplify/amplify-cli/issues/6898)

Any news when it will be ready? Some years already passed.

**Comment by vorant94** [comment]
@hackmajoris as a workaround i found this to be working perfectly fine

```yml
projects:
  functionsonsteroids:
    schemaPath: amplify/backend/api/functionsonsteroids/build/schema.graphql
    includes:
      - src/graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: angular
        generatedFileName: src/app/API.service.ts
        docsFilePath: src/graphql
        region: eu-central-1
        apiId: null
        maxDepth: 2


  lambdaShared:
    schemaPath: amplify/backend/api/functionsonsteroids/build/schema.graphql
    includes:
      - projects/lambda-shared/src/lib/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: projects/lambda-shared/src/lib/generated/app-sync.models.ts
        docsFilePath: projects/lambda-shared/src/lib/generated/
        region: eu-central-1
        apiId: null
        maxDepth: 2

extensions:
  amplify:
    version: 3
```
