### ISSUE TITLE
[request] offer to run `amplify codegen` directly after  `amplify configure codegen`

### ISSUE THREAD

**Issue by sw-yx** [aws-amplify/amplify-codegen#53]
**Describe the bug**

using `amplify configure codegen` to configure typescript code doesnt generate code.

**Amplify CLI Version**
4.24

**To Reproduce**

- have a very simple amplify init setup with a single graphql api in javascript (git repo here https://github.com/sw-yx/testamplify12121)
- then run `amplify configure codegen` and try to switch the generated code from javascript to typescript
- nothing happens

**Expected behavior**

- typescript code should be generated

**Screenshots**
![image](https://user-images.githubusercontent.com/6764957/87696311-3467f600-c7c3-11ea-81cc-92fd7758c6c2.png)

**Desktop (please complete the following information):**
 - OS: mac
 - Node Version. 12.8

**Comment by AaronZyLee** [comment]
@mogarick I am able to reproduce your issue. There is an indent issue with your YAML file. The `excludes` and `extensions` should be the children of `myapi`. The correct schema is as following.
```YAML
projects:
  myapi:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
      - ./src/graphql/GraphQLAPIClientAwsAmplify.ts
      - ./src/graphql/GraphQLServiceSyncManager.ts
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
extensions:
  amplify:
    version: 3
```
Once you have the correct indent, you are all set to use `amplify codegen configure`
