### ISSUE TITLE
amplify codegen add with all configs in a single command or read configs from a local file

### ISSUE THREAD

**Issue by ShengHow95** [aws-amplify/amplify-codegen#64]
**Is your feature request related to a problem? Please describe.**
My project now is creating multiple AppSync GraphQL API resources with `schema.graphql` using Cloudformation template. This `schema.graphql`  file is passed to my frontend hosted on Amplify (not using `amplify init`). It was possible to run `amplify codegen add` without the need to run `amplify init` and `amplify configure` in a folder with the `schema.graphql` file with Amplify CLI with some selections (such as Type of App, Javascript Framework, Code Generation Language etc). However, I wish to utilize this `amplify codegen add` during my frontend build on Amplify but I could not find ways to automate the configuration selections after running `amplify codegen add`. 

**Describe the solution you'd like**
**Proposed Solution 1:**: Accept arguments in a single command. For example,
`amplify codegen add --type=javascript --framework=vue --targetlanguage=javascript ......`

Or

**Proposed Solution 2:** Accept a config file such as `codegenconfig.yml` or `codegenconfig.json` that includes all required configuration and comes with command `amplify codegen add --config=./codegenconfig.yml`

**Sample Configuration**
![unnamed](https://user-images.githubusercontent.com/55613234/106988317-7c278c80-67aa-11eb-907f-a893455809c8.png)

**Comment by AaronZyLee** [comment]
We have a config file name `.graphqlconfig.yml`, which is generated after you run `amplify codegen add`. For now we do not support the headless command for codegen config. However, it is possible for your second proposed solution. Based on your sample image, you can add this `.graphqlconfig.yml` in advance and all you need is run `amplify codegen`. The code snippet is as following.
```YAML
projects:
  Codegen Project:
    schemaPath: schema.graphql
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        region: us-east-1
        apiId: null
        frontend: javascript
        framework: vue
        maxDepth: 2
```
This is my folder:
![image](https://user-images.githubusercontent.com/20614187/107098760-e0574a00-67c4-11eb-9ad0-fae23575c096.png)
This is how I run command:
![image](https://user-images.githubusercontent.com/20614187/107098796-f36a1a00-67c4-11eb-8ca5-b682d3e6fe68.png)
