### ISSUE TITLE
Amplify CLI 12.10 - No queries found to generate types for

### ISSUE THREAD

**Issue by farshid1** [aws-amplify/amplify-codegen#774]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

18.17.0

### Amplify CLI Version

12.10

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Describe the bug

after upgrading to v 12.10, `amplify codegen` is unable to create the `API.ts` file and returns the following error: `No queries found to generate types for, you may need to run 'codegen statements' first`

### Expected behavior

`API.ts` file is generated

### Reproduction steps

upgrade to cli v12.10. Run `amplify codegen`

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

Downgrading to 12.9 resolves the issue

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by flowappdev** [comment]
> Hey @farshid1, thank you for reaching out. Could you run `amplify diagnose --send-report` and provide us the `project identifier` output from the terminal.additionally, could you provide us the `.graphqlconfig.yml` file present at the root of the project. transferring to the codegen repository for further assistance.

sure thing.

Project identifier: 6fb09c4a6920b8cb8fb3a5f36cd8597d
`.graphqlconfig.yml`:

```
projects:
  flowa:
    schemaPath: amplify/backend/api/flowa/build/schema.graphql
    includes:
      - app/(graphql)/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: app/(graphql)/API.ts
        docsFilePath: app/(graphql)
        region: us-east-1
        apiId: null
        maxDepth: 3
extensions:
  amplify:
    version: 3
```

**Comment by farshid1** [comment]
> Hey @farshid1, thank you for reaching out. Could you run `amplify diagnose --send-report` and provide us the `project identifier` output from the terminal.additionally, could you provide us the `.graphqlconfig.yml` file present at the root of the project. transferring to the codegen repository for further assistance.

sure thing.

Project identifier: 6fb09c4a6920b8cb8fb3a5f36cd8597d
`.graphqlconfig.yml`:

```
projects:
  flowa:
    schemaPath: amplify/backend/api/flowa/build/schema.graphql
    includes:
      - app/(graphql)/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: app/(graphql)/API.ts
        docsFilePath: app/(graphql)
        region: us-east-1
        apiId: null
        maxDepth: 3
extensions:
  amplify:
    version: 3
```
